// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkuqvdcvxkqbpxljnjhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrdXF2ZGN2eGtxYnB4bGpuamhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTg3MDQsImV4cCI6MjA3MjU3NDcwNH0.8dGIyf7WrjI8YZB7B6-M4uuazfVHchLPDReSnEBaBl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});